name: humangenerator
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: null
  rxdart: null
  hive: null
  flame: ^0.29.4
  cupertino_icons: ^1.0.2
  file_picker: null
  flutter_neumorphic: ^3.1.0
  http: null
  image_picker: ^0.7.4
  path_provider: null
  splashscreen: null
  camera_deep_ar: ^0.0.1
  velocity_x: ^2.6.0
  connectivity: ^3.0.3
  font_awesome_flutter:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_colorpicker:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/audio/
    - assets/images/parallax/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Bee/
    - assets/images/BlueBird/
    - assets/images/Bunny/
    - assets/images/Chameleon/
    - assets/images/Chicken/
    - assets/images/Duck/
    - assets/images/FatBird/
    - assets/images/Ghost/
    - assets/images/Mushroom/
    - assets/images/Plant/
    - assets/images/Radish/
    - assets/images/Rino/
    - assets/images/Rocks/
    - assets/images/Skull/
    - assets/images/Slime/
    - assets/images/Snail/
    - assets/images/Trunk/
    - assets/images/Turtle/
    - assets/module_icons/
  fonts:
    - family: 'Lato'
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf